select "Angular coefficient",
"Explanatory variable",
cast(CONCAT("signal","coefficient") as numeric) as "Linear coefficient",
"Linear regression",
"Scheme",
"Relation",
"Instances",
"Attributes",
"Dependent variable",
"Test mode",
"Correlation coefficient",
"Mean absolute error",
"Root mean squared error",
"Relative absolute error",
"Root relative squared error",
"Total Number of Instances"
--into "2012_2017_quantidade".acre_2012_2017_quantidade_logaritimo 
	from (
	select 
	"Angular coefficient",
	split_part("Linear coefficient", ' ',1) as "signal",
	split_part("Linear coefficient", ' ',2) as "coefficient",
	"Linear coefficient",
	"Linear regression",
	"Scheme",
	"Relation",
	"Instances",
	"Attributes",
	"Explanatory variable",
	"Dependent variable",
	"Test mode",
	"Correlation coefficient",
	"Mean absolute error",
	"Root mean squared error",
	"Relative absolute error",
	"Root relative squared error",
	"Total Number of Instances" from (
		select 
		cast (split_part("Linear regression", '* Quantidade ln ',1) as numeric) as "Angular coefficient",
		split_part("Linear regression", '* Quantidade ln ',2) as "Linear coefficient",
		"Linear regression",
		"Scheme",
		"Relation",
		"Instances",
		"Attributes",
		"Explanatory variable",
		"Dependent variable",
		"Test mode",
		"Correlation coefficient",
		"Mean absolute error",
		"Root mean squared error",
		"Relative absolute error",
		"Root relative squared error",
		"Total Number of Instances" 
		from paraiba_2012_2017_valor_logaritimo) s)ss
		