create table comparacoes_2016_2018_v.espirito_santo_2016_2018 ("Ano" numeric,
 "valor ln" numeric,
 "valor ln ori" numeric,
 "Telha sem laje de concreto (mil pessoas)" numeric,
 "telha sem laje de concreto mil pessoas ori" numeric,
 "Telha com laje de concreto (mil pessoas)" numeric,
 "telha com laje de concreto mil pessoas ori" numeric,
 "Somente laje de concreto (mil pessoas)" numeric,
 "somente laje de concreto mil pessoas ori" numeric,
 "Madeira apropriada para construção (mil pessoas)" numeric,
 "madeira apropriada para construção mil pessoas ori" numeric,
 "Cimento (mil pessoas)" numeric,
 "cimento mil pessoas ori" numeric,
 "Cerâmica, lajota ou pedra (mil pessoas)" numeric,
 "cerâmica, lajota ou pedra mil pessoas ori" numeric,
 "Alvenaria/Taipa sem revestimento (mil pessoas)" numeric,
 "alvenaria/taipa sem revestimento mil pessoas ori" numeric,
 "Alvenaria/taipa com revestimento (mil pessoas)" numeric,
 "alvenaria/taipa com revestimento mil pessoas ori" numeric,
 "Madeira apropriada para construção (aparelhada) mil pessoas)" numeric,
 "madeira apropriada para construção aparelhada mil pessoas ori" numeric,
 "Queimado (na propriedade) mil pessoas)" numeric,
 "queimado na propriedade mil pessoas ori" numeric,
 "Outro destino (mil pessoas)" numeric,
 "outro destino mil pessoas ori" numeric,
 "Coletado em caçamba (mil pessoas)" numeric,
 "coletado em caçamba mil pessoas ori" numeric,
 "Coletado diretamente (mil pessoas)" numeric,
 "coletado diretamente mil pessoas ori" numeric,
 "Rede geral ou fossa ligada à rede (mil pessoas)" numeric,
 "rede geral ou fossa ligada à rede mil pessoas ori" numeric,
 "Outra forma de esgotamento (mil pessoas)" numeric,
 "outra forma de esgotamento mil pessoas ori" numeric,
 "Fossa não ligada à rede (mil pessoas)" numeric,
 "fossa não ligada à rede mil pessoas ori" numeric,
 "Rede geral ou fonte alternativa (mil pessoas)" numeric,
 "rede geral ou fonte alternativa mil pessoas ori" numeric,
 "Rede Geral (mil pessoas)" numeric,
 "rede geral mil pessoas ori" numeric,
 "Próprio de algum morador: Já pago (mil pessoas)" numeric,
 "próprio de algum morador: já pago mil pessoas ori" numeric,
 "Próprio de algum morador: Ainda pagando (mil pessoas)" numeric,
 "próprio de algum morador: ainda pagando mil pessoas ori" numeric,
 "Outra condição (mil pessoas)" numeric,
 "outra condição mil pessoas ori" numeric,
 "Cedido (mil pessoas)" numeric,
 "cedido mil pessoas ori" numeric,
 "Alugado (mil pessoas)" numeric,
 "alugado mil pessoas ori" numeric,
 "Outro combustível (mil pessoas)" numeric,
 "outro combustível mil pessoas ori" numeric,
 "Lenha ou carvão (mil pessoas)" numeric,
 "lenha ou carvão mil pessoas ori" numeric,
 "Gás de botijão ou encanado (mil pessoas)" numeric,
 "gás de botijão ou encanado mil pessoas ori" numeric,
 "Energia elétrica (mil pessoas)" numeric,
 "energia elétrica mil pessoas ori" numeric,
 "Casa (mil pessoas)" numeric,
 "casa mil pessoas ori" numeric,
 "Casa de cômodos, cortiço ou cabeça de porco (mil pessoas)" numeric,
 "casa de cômodos, cortiço ou cabeça de porco mil pessoas ori" numeric,
 "Apartamento (mil pessoas)" numeric,
 "apartamento mil pessoas ori" numeric,
 "Rede geral de distribuição (mil pessoas)" numeric,
 "rede geral de distribuição mil pessoas ori" numeric,
 "Poço raso, freático ou cacimba (mil pessoas)" numeric,
 "poço raso, freático ou cacimba mil pessoas ori" numeric,
 "Poço profundo ou artesiano (mil pessoas)" numeric,
 "poço profundo ou artesiano mil pessoas ori" numeric,
 "Outra forma de abastecimento (mil pessoas)" numeric,
 "outra forma de abastecimento mil pessoas ori" numeric,
 "Fonte ou nascente (mil pessoas)" numeric,
 "fonte ou nascente mil pessoas ori" numeric,
 "Canalizada (mil pessoas)" numeric,
 "canalizada mil pessoas ori" numeric);
insert into comparacoes_2016_2018_v.espirito_santo_2016_2018 ("Ano") values ('2016');
insert into comparacoes_2016_2018_v.espirito_santo_2016_2018 ("Ano") values ('2017');
insert into comparacoes_2016_2018_v.espirito_santo_2016_2018 ("Ano") values ('2018');

update comparacoes_2016_2018_v.espirito_santo_2016_2018
set "valor ln" = pivot_2016_2018_v.espirito_santo_2016_2018."valor ln"
from pivot_2016_2018_v.espirito_santo_2016_2018
where comparacoes_2016_2018_v.espirito_santo_2016_2018."Ano" = pivot_2016_2018_v.espirito_santo_2016_2018."Ano";


update {se}.{t} set "{vi}" = {si}.{t}."{vi}" from {si}.{t} where {se}.{t}."Ano" = {si}.{t}."Ano";
update {se}.{t} set "{vo} ori" = {sp}.{t}."{vo} ori" from {sp}.{t} where {se}.{t}."Ano" = {si}.{t}."Ano";
