#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 13 15:42:24 2020

@author: alexandre
"""

import pandas as pd
import sqlalchemy
import psycopg2
import time

conn = psycopg2.connect(host="localhost",database="natalice", user="postgres", password="postgres")
cur = conn.cursor()

engine = sqlalchemy.create_engine('postgresql://postgres:postgres@localhost:5432/natalice')

schemas_exportar = ['pivot']
schemas_extrair = ['arrumado']

tabelas_motivos = ['todos_os_hospitais_janeiro','todos_os_hospitais_fevereiro','todos_os_hospitais_marco','todos_os_hospitais_abril','todos_os_hospitais_maio','todos_os_hospitais_junho','todos_os_hospitais_julho','todos_os_hospitais_agosto','todos_os_hospitais_setembro','todos_os_hospitais_outubro','todos_os_hospitais_novembro','todos_os_hospitais_dezembro']

sql_raw = '''select motivo,count(motivo) as contagem from arrumado.{t} group by motivo'''
drop_table_raw = '''drop table if exists {ep}.{t}'''
create_table_raw = '''create table {ep}.{t} ()'''
insert_column_raw = '''ALTER TABLE {ep}.{t} ADD COLUMN if not exists {m} numeric'''
insert_into_raw = '''insert into {ep}.{t}({m}) values(0)'''
update_basic_raw = '''update {ep}.{t} set "{m}" = 0'''
update_raw = '''update {ep}.{t} set "{m}" = "{m}" + {v}'''

exportar = schemas_exportar[0]
schema = schemas_extrair[0]
listagem_tabelas = "SELECT  tablename  FROM   pg_catalog.pg_tables WHERE   schemaname = '{}' ;".format(schema)
lista_tabelas = pd.read_sql_query(listagem_tabelas,engine)
time.sleep(000)

#CRIAÇÃO DAS TABELAS E INSERÇÃO DAS COLUNAS NAS TABELAS////INICIO

for a in range(0,12):
    tabela_nova = tabelas_motivos[a]
    print(tabela_nova)
    drop_table = drop_table_raw.format(ep=exportar,t=tabela_nova)
    print('Executando drop table:')
    print('')
    print(drop_table)
    cur.execute(drop_table)
    create_table = create_table_raw.format(ep=exportar,t=tabela_nova)
    print('Executando create table:')
    print('')
    print(create_table)
    cur.execute(create_table)
    conn.commit()

#CRIAÇÃO DAS TABELAS////FIM
#INSERÇÃO DE COLUNAS////COMEÇO

for y in range(0,84):
    tabela = lista_tabelas.iloc[y,-1]

    if "jan" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_janeiro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
            
    if "fev" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_fevereiro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "mar" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_marco'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "abr" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_abril'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "mai" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_maio'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "jun" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_junho'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "jul" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_julho'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "ago" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_agosto'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "set" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_setembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "out" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_outubro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "nov" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_novembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()
        
    if "dez" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_dezembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            print('Coluna a ser inserida: {c}'.format(c=coluna))
            print('')
            time.sleep(0)
            insert_column_semi = insert_column_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            insert_column = insert_column_semi.replace("['",'"').replace("']",'"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(insert_column)
            print('')
            cur.execute(insert_column)           
            conn.commit()

#CRIAÇÃO DAS TABELAS E INSERÇÃO DAS COLUNAS NAS TABELAS E DADOS 0////FIM 
            
print('')          
print('Todos os processos foram concluídos')
print('')

#INSERÇÃO DE DADOS NAS TABELAS CRIADAS////INICIO
print('Listando tabelas novas:')   
print('')
listagem_tabelas_novas = "SELECT  tablename  FROM   pg_catalog.pg_tables WHERE   schemaname = '{}' ;".format(exportar)
print(listagem_tabelas_novas)
print('')
print('Tabelas novas listadas:')
print('')
lista_tabelas_novas = pd.read_sql_query(listagem_tabelas_novas,engine)
print(lista_tabelas_novas)
print('')
lar = len(lista_tabelas_novas.index)
print('Tamanho do dataframe: {lar}'.format(lar=lar))

for y in range(0,lar):
    tabela_nova = lista_tabelas_novas.iloc[y,-1]
    print('Listando colunas:')
    print('')
    listagem_colunas = '''select "column_name" from information_schema.columns where table_schema = '{ep}' and table_name = '{t}' '''.format(ep=exportar,t=tabela_nova)
    print(listagem_colunas)
    print('')
    print('Lista de colunas:')
    print('')
    lista_colunas = pd.read_sql_query(listagem_colunas,engine)
    print(lista_colunas)
    print('')
    print('Colunas listadas:')
    print('')
    colunas = lista_colunas.to_numpy()
    lenght = len(lista_colunas)
    conn.commit()
    
    
#COMEÇANDO INSERT INTO
    for x in range(0,1):
        coluna = (colunas[x])
        insert_into_semi = insert_into_raw.format(ep=exportar,t=tabela_nova,m=coluna)
        insert_into = insert_into_semi.replace("['",'"').replace("']",'"')
        print('Executando inserção de dados:')
        print('')
        print(insert_into)
        print('')
        cur.execute(insert_into)
        conn.commit()
        
#FIM DO INSERT INTO
    
#COMEÇANDO UPDATE BÁSICO
    
for y in range(0,84):
    tabela = lista_tabelas.iloc[y,-1]

    if "jan" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_janeiro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "fev" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_fevereiro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "mar" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_marco'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "abr" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_abril'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "mai" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_maio'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "jun" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_junho'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "jul" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_julho'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "ago" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_agosto'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "set" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_setembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "out" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_outubro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "nov" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_novembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
            
    if "dez" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_dezembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            time.sleep(0)
            update_basic_semi = update_basic_raw.format(ep=exportar,t=tabela_nova,m=coluna)
            update_basic = update_basic_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update_basic)
            print('')
            cur.execute(update_basic)           
            conn.commit()
#TERMINO DO UPDATE BASIC


#COMENÇANDO UPDATE PARA ADICIONAR VALORES

for y in range(0,84):
    tabela = lista_tabelas.iloc[y,-1]

    if "jan" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_janeiro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "fev" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_fevereiro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "mar" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_marco'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "abr" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_abril'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "mai" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_maio'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "jun" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_junho'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "jul" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_julho'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "ago" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_agosto'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "set" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_setembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "out" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_outubro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "nov" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_novembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()
            
    if "dez" in tabela:
        print(tabela)
        print('')
        tabela_nova = 'todos_os_hospitais_dezembro'
        print('Tabela nova:')
        print('')
        print(tabela_nova)
        print('')
        listagem_colunas = '''select motivo from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        lista_colunas = pd.read_sql_query(listagem_colunas,engine)
        print('Colunas: ')
        print('')
        colunas = lista_colunas.to_numpy()
        print(colunas)
        print('')
        contagem = '''select count(motivo) from {s}.{t} group by motivo'''.format(s=schema,t=tabela)
        numeros = pd.read_sql_query(contagem,engine)
        print('Valores: ')
        print('')
        valores = numeros.to_numpy()
        print(valores)
        print('')
        sql = sql_raw.format(t=tabela)
        df = pd.read_sql_query(sql,engine)
        print('Dataframe:')
        print('')
        print(df)
        print('')
        lenght = len(df.index)
        
        for x in range(0,lenght):
            coluna = (colunas[x])
            valor = (valores[x])
            print('Valor a ser inserido: {v}'.format(v=valor))
            print('')
            time.sleep(0)
            update_semi = update_raw.format(ep=exportar,t=tabela_nova,m=coluna,v=valor)
            update = update_semi.replace("['",'"').replace("']",'"').replace("[","").replace("]","").replace('""','"')
            print('Executando inserção de coluna: da tabela {t}'.format(t=tabela))
            print('')
            print(update)
            print('')
            cur.execute(update)           
            conn.commit()

conn.close()