update dados_agregados.pnad_mercado_e_populacao
set "Abertura Territorial" = 'Acre'
where "Abertura Territorial" = 'Acre ';

update dados_agregados.pnad_mercado_e_populacao
set	"Abertura Territorial" = 'Alagoas'
where "Abertura Territorial" = 'Alagoas ';

update dados_agregados.pnad_mercado_e_populacao
set	"Abertura Territorial" = 'Amazonas'
where "Abertura Territorial" = 'Amazonas ';

update dados_agregados.pnad_mercado_e_populacao
set	"Abertura Territorial" = 'Amapá'
where "Abertura Territorial" = 'Amapá ';

update dados_agregados.pnad_mercado_e_populacao
set	"Abertura Territorial" = 'Pará'
where "Abertura Territorial" = 'Pará ';

update dados_agregados.pnad_mercado_e_populacao
set	"Abertura Territorial" = 'Rondônia'
where "Abertura Territorial" = 'Rondônia ';

update dados_agregados.pnad_mercado_e_populacao
set	"Abertura Territorial" = 'Roraima'
where "Abertura Territorial" = 'Roraima ';

update dados_agregados.pnad_mercado_e_populacao
set	"Categoria.1" = 'Nuclear'
where "Categoria.1" = 'Nuclear ';

update dados_agregados.pnad_mercado_e_populacao
set "Categoria" = 'Agricultura, pecuária, produção florestal, pesca e aquicultura'
where "Categoria" = 'Agricultura, pecuária, produção florestal, pesca e aquicultura ';

update dados_agregados.pnad_mercado_e_populacao
set "Categoria" = 'Alojamento e alimentação'
where "Categoria" = 'Alojamento e alimentação ';

update dados_agregados.pnad_mercado_e_populacao
set "Categoria" = 'Transporte, armazenagem e correio'
where "Categoria" = 'Transporte, armazenagem e correio ';

drop table pivot.pnad_mercado_e_populacao_mil_pessoas;

select "Indicador" from dados_agregados.pnad_mercado_e_populacao group by "Indicador";

select k."Abertura Territorial"
,k."Ano"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Administração pública, defesa e seguridade social, educação, saúde humana e serviços sociais' then k."Valor" end) as "Administração pública"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Agricultura, pecuária, produção florestal, pesca e aquicultura' then k."Valor" end) as "Agricultura, pecuária e produção florestal"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Alojamento e alimentação' then k."Valor" end) as "Alojamento e alimentação"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Comércio, reparação de veículos automotores e motocicletas' then k."Valor" end) as "Comércio, reparação de veículos automotores e motocicletas"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Construção' then k."Valor" end) as "Construção"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Indústria geral' then k."Valor" end) as "Indústria geral"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Informação, comunicação e atividades financeiras, imobiliárias, profissionais e administrativas' then k."Valor" end) as "Informação, comunicação e atividades financeiras"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Outros Serviços' then k."Valor" end) as "Outros Serviços"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Serviços domésticos' then k."Valor" end) as "Serviços domésticos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Grupamentos de atividade no trabalho principal' and k."Categoria" like 'Transporte, armazenagem e correio' then k."Valor" end) as "Transporte, armazenagem e correio"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Nível de instrução' and k."Categoria" like 'Ensino fundamental completo e médio incompleto' then k."Valor" end) as "Ensino fundamental completo e médio incompleto"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Nível de instrução' and k."Categoria" like 'Ensino médio completo e superior incompleto' then k."Valor" end) as "Ensino médio completo e superior incompleto"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Nível de instrução' and k."Categoria" like 'Sem instrução e fundamental incompleto' then k."Valor" end) as "Sem instrução e fundamental incompleto"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Variável de abertura" like 'Nível de instrução' and k."Categoria" like 'Superior completo' then k."Valor" end) as "Superior completo"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Condição no domicílio' and k."Categoria.1" like 'Cônjuge ou companheiro(a)' then k."Valor" end) as "Cônjuge ou companheiro"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Condição no domicílio' and k."Categoria.1" like 'Filho(a) ou enteado(a)' then k."Valor" end) as "Filho ou enteado"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Condição no domicílio' and k."Categoria.1" like 'Outro' then k."Valor" end) as "Outro"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Condição no domicílio' and k."Categoria.1" like 'Responsável' then k."Valor" end) as "Responsável"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '0 a 4 anos' then k."Valor" end) as "0 a 4 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '5 a 9 anos' then k."Valor" end) as "5 a 9 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '5 a 13 anos' then k."Valor" end) as "5 a 13 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '10 a 13 anos' then k."Valor" end) as "10 a 13 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '14 a 15 anos' then k."Valor" end) as "14 a 15 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '14 a 17 anos' then k."Valor" end) as "14 a 17 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '16 a 17 anos' then k."Valor" end) as "16 a 17 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '18 a 19 anos' then k."Valor" end) as "18 a 19 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '20 a 24 anos' then k."Valor" end) as "20 a 24 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '25 a 29 anos' then k."Valor" end) as "25 a 29 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '30 a 39 anos' then k."Valor" end) as "30 a 39 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '40 a 49 anos' then k."Valor" end) as "40 a 49 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '50 a 59 anos' then k."Valor" end) as "50 a 59 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '60 a 64 anos' then k."Valor" end) as "60 a 64 anos"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Grupos de idade' and k."Categoria.1" like '65 anos ou mais' then k."Valor" end) as "65 anos ou mais"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Associação à cooperativa de trabalho ou produção' and k."Categoria.1" like 'Não estavam associadas à cooperativa de trabalho ou produção' then k."Valor" end) as "Não estavam associadas"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Associação à cooperativa de trabalho ou produção' and k."Categoria.1" like 'Estavam associadas à cooperativa de trabalho ou produção' then k."Valor" end) as "Estavam associadas"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Associação a sindicato' and k."Categoria.1" like 'Estavam associadas a sindicato' then k."Valor" end) as "Estavam associadas a sindicato"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Associação a sindicato' and k."Categoria.1" like 'Não estavam associadas a sindicato' then k."Valor" end) as "Não estavam associadas a sindicato"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em domicílio do empregador, patrão, sócio ou freguês' then k."Valor" end) as "Em domicílio do empregador, patrão, sócio ou freguês"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em estabelecimento de outro empreendimento' then k."Valor" end) as "Em estabelecimento de outro empreendimento"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em estabelecimento do próprio empreendimento' then k."Valor" end) as "Em estabelecimento do próprio empreendimento"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em fazenda, sítio, granja, chácara etc' then k."Valor" end) as "Em fazenda, sítio, granja, chácara etc"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em local designado pelo empregador, patrão ou freguês' then k."Valor" end) as "Em local designado pelo empregador, patrão ou freguês"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em outro local' then k."Valor" end) as "Em outro local"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em veículo automotor' then k."Valor" end) as "Em veículo automotor"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'Em via ou área pública' then k."Valor" end) as "Em via ou área pública"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Local de estabelecimento' and k."Categoria.1" like 'No domicílio de residência' then k."Valor" end) as "No domicílio de residência"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Registro do empreendimento no CNPJ' and k."Categoria.1" like 'Em empreendimento não registrado no CNPJ' then k."Valor" end) as "Empreendimento não registrado no CNPJ"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Registro do empreendimento no CNPJ' and k."Categoria.1" like 'Em empreendimento registrado no CNPJ' then k."Valor" end) as "Empreendimento registrado no CNPJ"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Tamanho do empreendimento' and k."Categoria.1" like '1 a 5 pessoas' then k."Valor" end) as "1 a 5 pessoas"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Tamanho do empreendimento' and k."Categoria.1" like '6 a 10 pessoas' then k."Valor" end) as "6 a 10 pessoas"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Tamanho do empreendimento' and k."Categoria.1" like '11 a 50 pessoas' then k."Valor" end) as "11 a 50 pessoas"
,sum(case when (k."Indicador" like 'Pessoas ocupadas (mil pessoas)' or k."Indicador" like 'População (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal em estabelecimento registrado no CNPJ (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas como empregadores ou conta própria no trabalho principal (mil pessoas)' or k."Indicador" like 'Pessoas ocupadas, exclusive os empregados no setor público e trabalhadores domésticos no trabalho principal (mil pessoas)' or "Indicador" like 'Pessoas ocupadas na semana de referência associadas a sindicato (mil pessoas)' or "Indicador" like 'Pessoas ocupadas no setor privado no trabalho principal, exclusive nos serviços domésticos (mil pessoas)' or "Indicador" like 'Pessoas ocupadas ou que anteriormente já foram ocupadas (mil pessoas)') and k."Categoria" like 'Total' and k."Variável de abertura.1" like 'Tamanho do empreendimento' and k."Categoria.1" like '51 ou mais pessoas' then k."Valor" end) as "51 ou mais pessoas"
into pivot.pnad_mercado_e_populacao_mil_pessoas
from
(select 
"Indicador"
,"Nível Territorial"
,"Abertura Territorial"
,"Variável de abertura"
,"Categoria"
,"Variável de abertura.1"
,"Categoria.1"
,2012 as "Ano"
,"2012" as "Valor"
from dados_agregados.pnad_mercado_e_populacao
union all
select 
"Indicador"
,"Nível Territorial"
,"Abertura Territorial"
,"Variável de abertura"
,"Categoria"
,"Variável de abertura.1"
,"Categoria.1"
,2013 as "Ano"
,"2013" as "Valor"
from dados_agregados.pnad_mercado_e_populacao
union all
select 
"Indicador"
,"Nível Territorial"
,"Abertura Territorial"
,"Variável de abertura"
,"Categoria"
,"Variável de abertura.1"
,"Categoria.1"
,2014 as "Ano"
,"2014" as "Valor"
from dados_agregados.pnad_mercado_e_populacao
union all
select 
"Indicador"
,"Nível Territorial"
,"Abertura Territorial"
,"Variável de abertura"
,"Categoria"
,"Variável de abertura.1"
,"Categoria.1"
,2015 as "Ano"
,"2015" as "Valor"
from dados_agregados.pnad_mercado_e_populacao
union all
select 
"Indicador"
,"Nível Territorial"
,"Abertura Territorial"
,"Variável de abertura"
,"Categoria"
,"Variável de abertura.1"
,"Categoria.1"
,2016 as "Ano"
,"2016" as "Valor"
from dados_agregados.pnad_mercado_e_populacao
union all
select 
"Indicador"
,"Nível Territorial"
,"Abertura Territorial"
,"Variável de abertura"
,"Categoria"
,"Variável de abertura.1"
,"Categoria.1"
,2017 as "Ano"
,"2017" as "Valor"
from dados_agregados.pnad_mercado_e_populacao) k 
where k."Nível Territorial" = 'Unidade da Federação'
group by "Abertura Territorial"
,k."Ano";
select * from pivot.pnad_mercado_e_populacao_mil_pessoas;


